# Project information
site_name: Central de Serviços
site_url: http://maismu-br.github.io/
site_author: maismu-br
site_description: >-
  Wiki +Mu - Manuais, procedimentos, guias rápidos e dicas, em um único lugar

# Repository
repo_url: https://github.com/maismu-br/maismu-br.github.io
edit_uri: edit/main/docs
# edit_uri_template: 'blob/main/docs/{path}'

# Copyright
copyright: © 2023 Company - Todos os direitos reservados

# Page tree
nav:
        - TI:
                - Introdução: index.md
                - Suporte:
                        - Softwares Homologados: suporte/softwares_homologados.md
                        - Assistência Rápida: suporte/assistencia_rap.md
                - Backup:
                        - Backup de Arquivos Importantes: backup/google_drive.md
                - Dicas e Truques:
                        - Atalhos do Windows 10: dicas-truques/atalhos_win.md
                        #- Atalhos do Excel:
                        - Aplicativos Úteis:
                                - Zoomlt: dicas-truques/aplicativos_uteis/Zoomlt.md
                                - FastStone Capture: dicas-truques/aplicativos_uteis/FastStone.md
                - Microsoft Office:
                        - Guias Rápidos do Office 365: office/guias_rapidos.md
                        - Guia Microsoft Teams: office/microsoft_teams.md
                - Mercos:
                        - Primeiro Acesso: mercos/primeiro_acesso.md
                        - Criando Roteiro: mercos/roteiro.md
                        - Importe Pedidos por Planilha: mercos/pedidos_via_planilha.md
                        - Indicadores: mercos/indicadores.md
                        - Aplicativo:
                                - Lançamento de Pedidos: mercos/aplicativo_lancar_pedido.md
                                - Enviando Pedidos para Faturamento: mercos/aplicativo_faturamento.md
                                - Sincronização: mercos/aplicativo_sincronizar.md
                - Segurança:
                        - Alterar Senha:
                                - Windows: seguranca/reset-senhas/reset_senha_windows.md
                                - Google: seguranca/reset-senhas/reset_senha_google.md
                                - Office: seguranca/reset-senhas/reset_senha_office.md
                        - Autenticação Multifator: seguranca/mfa.md     
                #- Hardware:
                        #- Formatando Equipamento: hardware/formatacao.md
                #- Menu exemplo:
                #        Submenu exemplo: suporte/faq.md
                #- Ajuda: sobre.md
        - Financeiro: 
                - Introdução: financeiro/introducao_financeiro.md
                - Política de Viagem:
                        - Objetivo: financeiro/viagem/viagem_objetivo.md
                        - Solicitação de Passagem: financeiro/viagem/viagem_passagens.md
                        - Solicitação de Hospedagem: financeiro/viagem/viagem_hospedagem.md
                        - Aumento de Limite/Prestação de Contas: financeiro/viagem/viagem_limite.md
                        - Locação de Veículos: financeiro/viagem/viagem_veiculo.md
                        - Alimentação: financeiro/viagem/viagem_alimentacao.md
                - Pagamento:
                        - Pagamentos: financeiro/pagamentos/pagamentos_geral.md
                        - Pagamentos Antecipados: financeiro/pagamentos/pagamentos_antecipados.md
                        - Pagamento de Contratos: financeiro/pagamentos/pagamento_contratos.md
                - Contas a Receber: financeiro/contas_a_receber.md
                - Conta Simples: financeiro/conta_simples.md
                - Reembolso: financeiro/reembolso.md
                - Brindes: financeiro/brindes.md
                - Informações da Mais Mu: financeiro/informacoes_gerais.md

# Configuration
theme:
        name: material
        custom_dir: overrides
        language: pt-BR
        #icon:
        #        logo: fontawesome/solid/computer
        logo: assets/images/logo-muka-white.png
        favicon: assets/images/mkdocs-favicon.png
        features:
                - announce.dismiss
                # - content.action.edit
                # - content.action.view
                - content.code.annotate
                - content.code.copy
                # - content.tabs.link
                - content.tooltips
                # - header.autohide
                #- navigation.expand
                - navigation.footer
                - navigation.indexes
                # - navigation.instant
                # - navigation.prune
                # - navigation.sections
                - navigation.tabs
                # - navigation.tabs.sticky
                - navigation.top
                - navigation.tracking
                - search.highlight
                - search.share
                - search.suggest
                - toc.follow
                # - toc.integrate
        palette:
                - scheme: default
                  primary: indico
                  accent: indico
                  toggle:
                    icon: material/brightness-7
                    name: Switch to dark mode
                - scheme: slate
                  primary: indico
                  accent: indico
                  toggle:
                    icon: material/brightness-4
                    name: Switch to light mode
        font:
                text: Roboto
                code: Roboto Mono


# Customization
extra:
        analytics:
                provider: google
                property: !ENV GOOGLE_ANALYTICS_KEY
        social:
                - icon: fontawesome/brands/instagram
                  link: https://www.instagram.com/maismu
                #- icon: fontawesome/brands/youtube
                #  link: https://www.youtube.com/channel/fconhkd
                - icon: fontawesome/brands/linkedin
                  link: https://www.linkedin.com/company/maismu/
                #- icon: fontawesome/brands/facebook
                #  link: https://www.facebook.com/fconhkd
                - icon: fontawesome/brands/github
                  link: https://github.com/maismu-br

                  
        caption: true
        lazy_load: true
        align: center
        generator: false

# CSS e Javascript
extra_css:
    - 'assets/css/extra.css'
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
    - assets/javascripts/highlight.js

# Plugins
plugins:
        - search:
                lang: pt
        - minify:
                minify_html: true
        - git-revision-date-localized:
                enabled: !ENV [CI, false]
                enable_creation_date: true
                fallback_to_build_date: true
                type: timeago

# Extensions
markdown_extensions:
        - abbr
        - admonition
        - attr_list
        - def_list
        - footnotes
        - md_in_html
        #- toc:
        #        permalink: true
        - pymdownx.arithmatex:
                generic: true
        - pymdownx.betterem:
                smart_enable: all
        - pymdownx.caret
        - pymdownx.details
        - pymdownx.emoji:
                emoji_generator: !!python/name:materialx.emoji.to_svg
                emoji_index: !!python/name:materialx.emoji.twemoji
        - pymdownx.highlight:
                anchor_linenums: true
                line_spans: __span
                pygments_lang_class: true
        - pymdownx.inlinehilite
        - pymdownx.snippets
        - pymdownx.keys
        - pymdownx.magiclink:
                repo_url_shorthand: true
                user: maismu-br
                repo: maismu-br.github.io
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
                custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.tabbed:
                alternate_style: true
        - pymdownx.tasklist:
                custom_checkbox: true
        - pymdownx.tilde
        
