name: 🚀 Deploy website on push
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          GIT_DEPTH: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          
#      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
#      - uses: actions/cache@v3
#        with:
#          key: mkdocs-material-${{ env.cache_id }}
#          path: .cache
#          restore-keys: |
#            mkdocs-material-
      
      - name: 🔨 Install dependencies
        run: |
          pip install --upgrade --force-reinstall mkdocs-material
          pip install mkdocs-material-extensions
          pip install mkdocs-minify-plugin
          pip install mkdocs-autorefs
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-glightbox
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-markdownextradata-plugin

      - name: 🔨 Clean
        run: mkdocs build -c

      - name: 🤳 Deploy website
        run: mkdocs gh-deploy --force
